# 应用服务 WEB 访问端口
server:
  port: 7090
  servlet:
    context-path: /api
  # session 过期时间 60M 一个小时
  reactive:
    session:
      timeout: PT60M
#异常处理
spring:
  mvc:
    # 处理 favicon
    favicon:
      enabled: false
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  #数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/easypan?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HiKariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-test-query: SELECT 1
  mail:
    #发送邮件配置相关
    # 配置邮件服务器的地址 smtp.qq.com
    host: smtp.qq.com
    # 配置邮件服务器的端口
    port: 465
    # 配置用户的账号
    username: 3032691368@qq.com
    # 配置用户的授权码 zstnqsfydwksdfab
    password: zstnqsfydwksdfab
    # 配置默认编码
    default-encoding: utf-8
    # SSL 连接配置
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        # 开启 debug，这样方便开发者查看邮件发送日志
        debug: true
  #Spring redis配置
  # Redis数据库索引（默认为0）
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 2000


#项目目录
project:
  folder: G:/Programs/workspace/workspace01-java/easypan/
#日志级别配置
log:
  root:
    level: debug
#超级管理员id
admin:
  emails: 3032691368@qq.com
#是否是开发环境
dev: false

## qq登录相关 ##
